In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([8,7,6,5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]


In [5]:
type(a)

numpy.ndarray

In [6]:
print(a+b)
print(a-b)
print(a*b)

[9 9 9 9 9 9 9 9]
[-7 -5 -3 -1  1  3  5  7]
[ 8 14 18 20 20 18 14  8]


In [7]:
#creating a 2d array
a2 = np.array([[1,2],[3,4]])
print(a2)

[[1 2]
 [3 4]]


In [8]:
#3D array
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
print(a2. shape)
print(a2.ndim)
print(a2.dtype)

(2, 2)
2
int64


In [10]:
lst=[]
for i in range(1,21):
    lst.append(i)
    print(lst)

[1]
[1, 2]
[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [11]:
np.arange(10)
np.arange(2,21)
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
np.random.randint(1,11, size=(2,3))

array([[1, 5, 8],
       [6, 9, 4]], dtype=int32)

In [14]:
x= np.array([[7,2,3],
             [2,5,2],
             [3,5,1]])
y = np.array([[1,8,3],
              [3,7,2],
              [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [15]:
print(x*y)

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [16]:
print(x@y)

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [17]:
np.dot(x,y)#matrix multiplication

array([[19, 85, 34],
       [21, 61, 22],
       [20, 64, 22]])

In [18]:
x.prod()#product of all elements of the array

np.int64(12600)

In [19]:
x.mean()#mean of all element

np.float64(3.3333333333333335)

In [20]:
y.mean()#mean of all element

np.float64(3.7777777777777777)

In [21]:
x.mean(axis = 0)#column wise mean

array([4., 4., 2.])

In [22]:
y.mean(axis = 1)#row wise mean

array([4.        , 4.        , 3.33333333])

In [23]:
print (x.sum())
print (x.std())
print (x.var())

30
1.8257418583505538
3.3333333333333335


In [24]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25))#1st quartile
print(np.percentile(a,50))#median
print(np.percentile(a,75))#3rd quartile

3.0
5.0
7.0


In [25]:
b = np.random.randint(11,100,(4,4))
print(b)

[[84 93 62 25]
 [72 41 55 27]
 [59 21 95 17]
 [67 74 94 98]]


In [26]:
print('2x8')
print(b.reshape(2,8))
print('8x2')
print(b.reshape(8,2))

2x8
[[84 93 62 25 72 41 55 27]
 [59 21 95 17 67 74 94 98]]
8x2
[[84 93]
 [62 25]
 [72 41]
 [55 27]
 [59 21]
 [95 17]
 [67 74]
 [94 98]]


In [27]:
x = np.random.randint(1,11 ,(5,5))
print(x)

[[10  3  9  5  1]
 [ 2 10  4  3  4]
 [ 2  4  6  6  7]
 [10  9  7  4 10]
 [ 5  6  9 10  8]]


In [28]:
print(x[0])#1st row
print(x[0,1])#1st row and 2nd column's first element
print(x[-1])

print(x[:3])
print(x[3:])

[10  3  9  5  1]
3
[ 5  6  9 10  8]
[[10  3  9  5  1]
 [ 2 10  4  3  4]
 [ 2  4  6  6  7]]
[[10  9  7  4 10]
 [ 5  6  9 10  8]]
